version: '3'
services:
  hono:
    build:
      context: .
      dockerfile: Dockerfile.Hono
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ./src:/usr/app/src
    networks:
      - app-network
  postgresql:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 25432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - app-network
networks:
  app-network:
